en_wiki_selected = [
    'Phenomena such as civilisation, technology (e.g.',
    'Belief in political nihilism has been espoused by anarchists.',
    'In contemporary anarchism, this current survives as a tendency to support polyamory and queer anarchism.',
    'As it appeals to both emotion and reason, art could appeal to the whole human and have a powerful effect.',
    '), economic class systems (e.g., capitalism, Bolshevism, feudalism, slavery, etc.',
    'Anarchism pays significant attention to moral arguments since ethics have a central role in anarchist philosophy.',
    'Nonetheless, his ideas formed the inspiration for a series of modern schools around the world.',
    'Anarchic attitudes were also articulated by tragedians and philosophers in Greece.',
    'Mutualism is an 18th-century economic theory that was developed into anarchist theory by Pierre-Joseph Proudhon.',
    'Anarchism is usually placed on the far-left of the political spectrum.',
    'Anarchism became associated with punk subculture as exemplified by bands such as Crass and the Sex Pistols.',
    'The school closed after constant harassment by the state and Ferrer was later arrested.',
    'In music, anarchism has been associated with music scenes such as punk.',
    'Those anarchists also built communities which were based on friendship and were involved in the news media.',
    'Three overlapping properties made art useful to anarchists.',
    'A significant event of this period was the confrontations at the 1999 Seattle WTO conference.',
    'Criticism of anarchism include claims that it is internally inconsistent, violent, or utopian.',
    'Anarchism and the state Objection to the state and its institutions is a sine qua non of anarchism.',
    'Post-war era At the end of World War II, the anarchist movement was severely weakened.',
    'Overall, contemporary anarchists are much less violent and militant than their ideological ancestors.',
    'Tokyo was a hotspot for rebellious youth from countries of the far east, travelling to the Japanese capital to study.',
    'Members of The Invisible Committee were arrested in 2008 on various charges, terrorism included.',
    'Beliefs on how to abolish the state also differ.',
    'These, and other Muslim movements, later gave birth to religious anarchism.',
    'Anarchist tactics have shifted during the course of the last century.',
    'Anarchism is broadly used to describe the anti-authoritarian wing of the socialist movement.',
    'Anarchists were also involved in developing various software that are available for free.',
    'In response to their expulsion from the First International, anarchists formed the St. Imier International.',
    'In medieval Europe, there was no anarchistic activity except some ascetic religious movements.',
    'The decision-making process of small anarchist affinity groups plays a significant tactical role.',
    "Raz believes that this argument is true in following both authorities' successful and mistaken instruction.",
    'This line of arguments most often calls for political action within the system to reform it.',
    'They were followed by the major currents of social anarchism (collectivist, communist and syndicalist).',
    'Marxists state that this contradiction was responsible for their inability to act.',
    'Alongside Stoicism, Taoism has been said to have had "significant anticipations" of anarchism.',
    'This coincided with its failure to gain traction in Northern Europe and its unprecedented height in Latin America.',
    'During this time, a minority of anarchists adopted tactics of revolutionary political violence.',
    'Anarchism calls for the abolition of the state, which it holds to be unnecessary, undesirable, and harmful.',
    "The basic principles of anarcho-syndicalism are direct action, workers' solidarity and workers' self-management.",
    'The most notable precursors to anarchism in the ancient world were in China and Greece.',
    'Evolutionary tactics Anarchists commonly employ direct action.',
    'Secondly, anarchism is evaluated as unfeasible or utopian since the state cannot be defeated practically.',
    'One of the earliest criticisms is that anarchism defies and fails to understand the biological inclination to authority.',
    'In Europe, various sects developed anti-state and libertarian tendencies.',
    'Anarchist thought, criticism, and praxis have played a part in diverse areas of human society.',
    'After bitter disputes, the Bakuninists were expelled from the International by the Marxists at the 1872 Hague Congress.',
    'Anarchists also took part in revolutions.',
    "Black anarchism began to take form at this time and influenced anarchism's move from a Eurocentric demographic.",
    'Various anarchist schools of thought formed during this period.',
    'Anarchists also reinforced their propaganda within the arts, some of whom practiced naturism and nudism.',
    'An argument for philosophical anarchism.',
    'Other anarchist groups advocate direct action, a tactic which can include acts of sabotage or terrorism.',
    'Although traces of anarchist thought are found throughout history, modern anarchism emerged from the Enlightenment.',
    'Those anarchists would rather base their thought and praxis on their own experience which they will later theorize.',
    'History Pre-modern era Before the establishment of towns and cities, an established authority did not exist.',
    'Anarchist and non-anarchist feminists differed on suffrage but were supportive of one another.',
    'Anarchism is contrasted to socialist forms which are state-oriented or from above.',
    'They differ on organisational and economic aspects of their ideal society.',
    'In Basra, religious sects preached against the state.',
    'Illegalism was another strategy which some anarchists adopted during this period.',
    'With the rise of organised hierarchical bodies, scepticism toward authority also rose.',
    'Acquiring space enables anarchists to experiment with their ideas and build social bonds.',
    'Early influences on individualist forms of anarchism include William Godwin, Max Stirner, and Henry David Thoreau.',
    'Anarchists organize themselves to squat and reclaim public spaces.',
    'Instead of people being able to control the aspects of their life, major decisions are taken by a small elite.',
    'Collectivist anarchism is a revolutionary socialist form of anarchism commonly associated with Mikhail Bakunin.',
    'Classical era tactics During the classical era, anarchists had a militant tendency.',
    'Classical Inceptive currents among classical anarchist currents were mutualism and individualism.',
    'A historical current that arose and flourished during 1890 and 1920 within anarchism was free love.',
    'Anarchists were treated similarly in the Second International, being ultimately expelled in 1896.',
    'At the turn of the century, anarchism had spread all over the world.',
    'In the last decades of the 20th and into the 21st century, the anarchist movement has been resurgent once more.',
    'Cynics dismissed human law (nomos) and associated authorities while trying to live according to nature (physis).',
    'This strategy became known as propaganda of the deed.',
    'Ferrer aimed to educate the working class and explicitly sought to foster class consciousness among students.',
    'Assassination attempts were carried out against heads of state, some of which were successful.',
    'A defence of philosophical anarchism, stating that "both kinds of \'anarchism\' [i.e.',
    '), autocratic religions (e.g., fundamentalist Islam, Roman Catholicism, etc.',
    'It was after the creation of institutions of authority that anarchistic ideas espoused as a reaction.',
    'A long tradition of Spanish anarchism led to anarchists playing a pivotal role in the war.',
    'The anti-capitalist tradition of classical anarchism has remained prominent within contemporary currents.',
    'philosophical and political anarchism] are philosophical and political claims."',
    '(1840), Proudhon first characterised his goal as a "third form of society, the synthesis of communism and property."',
    '), patriarchy, heterosexism, white supremacy, and imperialism."',
    'It was a notable feature of the international syndicalism movement.',
    'Anarchists usually form small groups (5–20 individuals) to enhance autonomy and friendships among their members.',
    'It also saw a transition from its previous revolutionary nature to provocative anti-capitalist reformism.',
    'In China, small groups of students imported the humanistic pro-science version of anarcho-communism.',
    'The established feminist tendencies of anarcha-feminism returned with vigour during the second wave of feminism.',
    'Post-classical and contemporary Anarchist principles undergird contemporary radical social movements of the left.',
    'Anarcho-pacifists advocate for non-violence means to achieve their stateless, nonviolent ends.',
    '(p. 137) Anarchistic popular fiction novel.',
    'Anarchy Archives is an online research center on the history and theory of anarchism.',
    'Humans lived in societies without formal hierarchies long before the establishment of formal states, realms, or empires.',
    'Anarchist schools disagree on the methods by which these forms should be opposed.',
    'Specific anarchist attitudes towards the state vary.',
    'The suffix -ism denotes the ideological current that favours anarchy.',
    'Contemporary anarchists such as Ward claim that state education serves to perpetuate socioeconomic inequality.',
    'In the anarchist vision, the conflict between liberty and equality was resolved through coexistence and intertwining.',
    'They saw it as a part of the movement which sought to overthrow the state and capitalism.',
    'These kinds of groups more often than not interconnect with each other, forming larger networks.',
    'In literature, anarchism was mostly associated with the New Apocalyptics and the neo-romanticism movement.',
    'Socrates questioned Athenian authorities constantly and insisted on the right of individual freedom of conscience.',
    'As the movement shaped 21st century radicalism, wider embrace of anarchist principles signaled a revival of interest.',
    'The third argument is that anarchism is self-contradictory.',
    'Other anarchists advocated for or used art as a means to achieve anarchist ends.',
    'Anarchist perspectives towards violence have always been controversial.',
    'Many autistic people face significant obstacles in transitioning to adulthood.',
    'In the other two studies, whose duration was 3 months, no significant effect was observed.',
    'For them, the quality of friendships, not the number of friends, predicts how lonely they feel.',
    'However, most of the mutations that increase autism risk have not been identified.',
    'No two-word (spontaneous, not just echolalic) phrases by 24 months.',
    'Globally, autism is estimated to affect 24.8 million people .',
    'Events include World Autism Awareness Day, Autism Sunday, Autistic Pride Day, Autreat, and others.',
    'Making and maintaining friendships often proves to be difficult for autistic people.',
    'Metabolic and neuroimaging tests are sometimes helpful, but are not routine.',
    'It is not known how often this outcome happens; reported rates in unselected samples have ranged from 3% to 25%.',
    'Masking may include making oneself perform normative facial expressions and eye contact.',
    'Autistic children may have difficulty with imaginative play and with developing symbols into language.',
    'In the 2000s, the number of autistic people worldwide was estimated at 1–2 per 1,000 people.',
    'Chelation is not recommended for autistic people since the associated risks outweigh any potential benefits.',
    'They may also be used for associated health problems, such as ADHD or anxiety.',
    'Intrauterine growth restriction is associated with ASD, in both term and preterm infants.',
    'Delay in referral for such testing may delay early diagnosis and treatment and affect the long-term outcome".',
    'Autism is associated with a combination of genetic and environmental factors.',
    'Parents of children with ASD have higher levels of stress.',
    'Among those who find work, most are employed in sheltered settings working for wages below the national minimum.',
    'Families and the educational system are the main resources for treatment.',
    'Males are at higher risk for ASD than females.',
    'Many autistic children lack social support, future employment opportunities or self-determination.',
    'Minor physical anomalies are significantly increased in the autistic population.',
    'Ritualistic behavior: Unvarying pattern of daily activities, such as an unchanging menu or a dressing ritual.',
    'The Diagnostic interview for social and communication disorders (DISCO) may also be used.',
    'It is not known which approach is more effective.',
    'Most loci individually explain less than 1% of cases of autism.',
    'Many autistic individuals have been successful in their fields.',
    'Self-injury: Behaviors such as eye-poking, skin-picking, hand-biting and head-banging.',
    'History A few examples of autistic symptoms and treatments were described long before autism was named.',
    'Society and culture An autistic culture has emerged, accompanied by the autistic rights and neurodiversity movements.',
    'Conversely, the cost of screening and diagnosis and the challenge of obtaining payment can inhibit or delay diagnosis.',
    'Studies of interventions have methodological problems that prevent definitive conclusions about efficacy.',
    'Autistic people may be severely impaired in some respects but average, or even superior, in others.',
    'Side effects, for example, may include weight gain, tiredness, drooling, and aggression.',
    'In 2012, the NHS estimated that the overall prevalence of autism among adults aged 18 years and over in the UK was 1.1%.',
    'Exposure to air pollution during pregnancy, especially heavy metals and particulates, may increase the risk of autism.',
    'Numerous candidate genes have been located, with only small effects attributable to any particular gene.',
    "A genotype-first model of diagnosis has been proposed, which would routinely assess the genome's copy number variations.",
    'Studies on pet therapy have shown positive effects.',
    'Prognosis There is no known cure for autism.',
    'It has been proposed to classify autism using genetics as well as behavior.',
    'Globally, autism affects an estimated 24.8 million people , while Asperger syndrome affects a further 37.2 million.',
    'Epilepsy, with variations in risk of epilepsy due to age, cognitive level, and type of language disorder.',
    'Functional friendships, such as those resulting in invitations to parties, may affect the quality of life more deeply.',
    'In general, higher IQs are correlated with greater responsiveness to treatment and improved treatment outcomes.',
    'CDC estimates about 1 out of 59 (1.7%) for 2014, an increase from 1 out of every 68 children (1.5%) for 2010.',
    'Sameness: Resistance to change; for example, insisting that the furniture not be moved or refusing to be interrupted.',
    'About half of people in their 20s with autism are not employed.',
    "No known medication relieves autism's core symptoms of social and communication impairments.",
    'In May 2013, the DSM-5 was released, updating the classification for pervasive developmental disorders.',
    'Several diagnostic instruments are available.',
    'Autistic females have been shown to engage in masking more frequently than autistic males.',
    'Although core difficulties tend to persist, symptoms often become less severe with age.',
    'It took until 1980 for the DSM-III to differentiate autism from childhood schizophrenia.',
    "No single treatment is best and treatment is typically tailored to the child's needs.",
    'A majority of the economic burden of autism is caused by decreased earnings in the job market.',
    'Several metabolic defects, such as phenylketonuria, are associated with autistic symptoms.',
    'This is closely associated with sameness and an independent validation has suggested combining the two factors.',
    'A 2016 survey in the United States reported a rate of 25 per 1,000 children for ASD.',
    'ICD-10 uses essentially the same definition.',
    'Epidemiology As of 2007, reviews estimate a prevalence of 1–2 per 1,000 for autism and close to 6 per 1,000 for ASD.',
    'The behaviors appear to have multiple pathophysiologies.',
    'How autism occurs is not well understood.',
    'In the developed countries, about 1.5% of children are diagnosed with ASD , up from 0.7% in 2000 in the United States.',
    'It is diagnosed four to five times more often in males than females.',
    'Other aspects, such as atypical eating, are also common but are not essential for diagnosis.',
    'In contrast, in the UK, children whose families or doctors recognize possible signs of autism are screened.',
    'Loss of any language or social skills, at any age.',
    'Some studies also find decreased earning among parents who care for autistic children.',
    'Most professionals believe that race, ethnicity, and socioeconomic background do not affect the occurrence of autism.',
    'This includes decreasing stress, anxiety, ruminating thoughts, anger, and aggression.',
    'In 1987, the DSM-III-R provided a checklist for diagnosing autism.',
    'As new genetic tests are developed several ethical, legal, and social issues will emerge.',
    'Few high-quality studies address long-term prognosis.',
    'However, they do form attachments to their primary caregivers.',
    'Maternal nutrition and inflammation during preconception and pregnancy influences fetal neurodevelopment.',
    'In 2005, botched chelation therapy killed a five-year-old child with autism.',
    'The presence of autism can make it harder to diagnose coexisting psychiatric disorders such as depression.',
    'Autistic people have social impairments and often lack the intuition about others that many people take for granted.',
    'Unusual social development becomes apparent early in childhood.',
    'Employment About half of autistic people are unemployed, and one third of those with graduate degrees may be unemployed.',
    'Signs of autism may be more challenging for clinicians to detect in females.',
    'Many genes have been associated with autism through sequencing the genomes of affected individuals and their parents.',
    'Many individuals with ASD show superior skills in perception and attention, relative to the general population.',
    'Starting in the late 1960s autism was established as a separate syndrome.',
    'Some, such as the MMR vaccine, have been completely disproven.',
    'Therapy also aims to reduce challenging behaviors and build upon strengths.',
    'Gastrointestinal problems are one of the most commonly co-occurring medical conditions in autistic people.',
    'There are many anecdotal reports, but few systematic studies, of aggression and violence in individuals with ASD.',
    'Some rare mutations may lead to autism by disrupting some synaptic pathways, such as those involved with cell adhesion.',
    'There has been early research looking at hyperbaric treatments in children with autism.',
    'Compared to the general population autistic people are more likely to be unemployed and to have never had a job.',
    'Several other conditions are common in children with autism.',
    'Several lines of evidence point to synaptic dysfunction as a cause of autism.',
    'Unlike with autism, people with Asperger syndrome have no substantial delay in language development.',
    'However, the development of evidence-based interventions has advanced in recent years.',
    'Sleep problems affect about two-thirds of individuals with ASD at some point in childhood.',
    'These symptoms do not imply sickness, fragility, or emotional disturbance.',
    'Some autistic adults are unable to live independently.',
    'In the UK, from 1998 to 2018, the autism diagnoses increased by 787%.',
    'Stereotyped behaviors: Repetitive movements, such as hand flapping, head rolling, or body rocking.',
    'Parents may first become aware of autistic symptoms in their child around the time of a routine vaccination.',
    'No response to name (or eye-to-eye gaze) by 6 months.',
    'There is evidence that gut–brain axis abnormalities may be involved.',
    "Mechanism Autism's symptoms result from maturation-related changes in various systems of the brain.",
    'This perspective is distinct from fringe theories that autism is caused by environmental factors such as vaccines.',
    'Diagnosis Diagnosis is based on behavior, not cause or mechanism.',
    "Parents often notice signs during the first three years of their child's life.",
    'Some alternative treatments may place the child at risk.',
    'Selectivity is the most common problem, although eating rituals and food refusal also occur.',
    'It is not known whether Kanner derived the term independently of Asperger.',
    "Albedo–temperature feedback When an area's albedo changes due to snowfall, a snow–temperature feedback results.",
    'Clouds Cloud albedo has substantial influence over atmospheric temperatures.',
    'This feedback loop results in a reduced albedo effect.',
    'That said, albedo and illumination both vary by latitude.',
    'This is far higher than for the ocean primarily because of the contribution of clouds.',
    'The uneven heating of Earth from albedo variations between land, ice, or ocean surfaces can drive weather.',
    'Over Antarctica snow albedo averages a little more than 0.8.',
    'Snow on top of this sea ice increases the albedo to 0.9.',
    'Small-scale effects Albedo works on a smaller scale, too.',
    'Sea water absorbs more solar radiation than would the same surface covered with reflective snow.',
    "Fresh 'black' ice exhibits Fresnel reflection.",
    'If only the continental land masses became covered by glaciers, the mean temperature of the planet would drop to about .',
    '"On any given day, about half of Earth is covered by clouds, which reflect more sunlight than land and water.',
    'Albedo is highest near the poles and lowest in the subtropics, with a local maximum in the tropics.',
    'Unless given for a specific wavelength (spectral albedo), albedo refers to the entire spectrum of solar radiation.',
    'One of these five parameters is yet another type of albedo called the single-scattering albedo.',
    'Both positive feedback loops have long been recognized as important for global warming.',
    'However, as mentioned above, waviness causes an appreciable reduction.',
    'BDRF can facilitate translations of observations of reflectance into albedo.',
    'The average albedo of Earth is about 0.3.',
    'Water Water reflects light very differently from typical terrestrial materials.',
    'and the echo from the target is measured.',
    'Aerosols modify the properties of clouds through a subset of the aerosol population called cloud condensation nuclei.',
    'Arctic regions notably release more heat back into space than what they absorb, effectively cooling the Earth.',
    'Aerosols directly scatter and absorb radiation.',
    'If Earth were frozen entirely (and hence be more reflective), the average temperature of the planet would drop below .',
    'Trees also impact climate in extremely complicated ways through evapotranspiration.',
    'It is used to define scattering of electromagnetic waves on small particles.',
    'The reflectivity of a water surface is calculated using the Fresnel equations.',
    'Surface albedo is defined as the ratio of radiosity Je to the irradiance Ee (flux per unit area) received by a surface.',
    "Earth's average surface temperature due to its albedo and the greenhouse effect is currently about .",
    'A layer of snowfall increases local albedo, reflecting away sunlight, leading to local cooling.',
    'Most land areas are in an albedo range of 0.1 to 0.4.',
    'Their values can differ significantly, which is a common source of confusion.',
    'Climate and weather Albedo affects climate by determining how much radiation a planet absorbs.',
    'Cryoconite, powdery windblown dust containing soot, sometimes reduces albedo on glaciers and ice sheets.',
    'Radar Albedo In planetary radar astronomy, a microwave (or radar) pulse is transmitted toward a planetary target (e.g.',
    'Deeply shadowed cavities can achieve an effective albedo approaching the zero of a black body.',
    'A typical comet nucleus has an albedo of 0.04.',
    'The extra absorbed energy heats the sea water, which in turn increases the rate at which sea ice melts.',
    'The glint of light off water is a commonplace effect of this.',
    'Black carbon Another albedo-related effect on the climate is from black carbon particles.',
    'The scattering of radiation causes atmospheric cooling, whereas absorption can cause atmospheric warming.',
    'This may have both been co-caused by climate change as well as a substantial increase in global warming.',
    'Deciduous trees have an albedo value of about 0.15 to 0.18 whereas coniferous trees have a value of about 0.09 to 0.15.',
    'These factors vary with atmospheric composition, geographic location, and time (see position of the Sun).',
    'Solar photovoltaic effects Albedo can affect the electrical energy output of solar photovoltaic devices.',
    'Another notable high-albedo body is Eris, with an albedo of 0.96.',
    'The term albedo was introduced into optics by Johann Heinrich Lambert in his 1760 work Photometria.',
    'Clouds keep Earth cool by reflecting sunlight, but they can also serve as blankets to trap warmth."',
    'Many small objects in the outer Solar System and asteroid belt have low albedos down to about 0.05.',
    'It is similar in shape to the Ancient Greek letter alpha, from which it derives.',
    'The Roman form is used in most printed material; it consists of a small loop with an arc over it ("a").',
    'are used to denote segments, lines, rays, etc.',
    'Its name in English is a (pronounced ), plural aes.',
    'Finally, the letter A is used to denote size, as in a narrow size shoe, or a small cup size in a brassiere.',
    'The lowercase version can be written in two forms: the double-storey a and single-storey ɑ.',
    'An exception is Saanich, in which (and the glyph Á) stands for a close-mid front unrounded vowel .',
    'Graphic designers refer to the Italic and Roman forms as "single decker a" and "double decker a" respectively.',
    'in X-SAMPA, is used for the open front unrounded vowel and is used for the open back unrounded vowel.',
    'However, occurs in many common digraphs, all with their own sound or sounds, particularly , , , , and .',
    'First was the monumental or lapidary style, which was used when inscribing on stone or other "permanent" media.',
    'This form was derived through a combining of prior forms.',
    'Variants also existed that were intermediate between the monumental and cursive styles.',
    'In the English grammar, "a", and its variant "an", are indefinite articles.',
    'The Etruscans brought the Greek alphabet to their civilization in the Italian Peninsula and left the letter unchanged.',
    'Many fonts then made the right leg vertical.',
    'The known variants include the early semi-uncial, the uncial, and the later semi-uncial.',
    'Typographic variants During Roman times, there were many variant forms of the letter "A".',
    'In English grammar, "a", and its variant "an", is an indefinite article, used to introduce noun phrases.',
    'A, or a, is the first letter and the first vowel of the modern English alphabet and the ISO basic Latin alphabet.',
    'These variants, the Italic and Roman forms, were derived from the Caroline Script version.',
    'The uppercase version consists of the two slanting sides of a triangle, crossed in the middle by a horizontal bar.',
    '"A" is used as a prefix on some words, such as asymmetry, to mean "not" or "without" (from Greek).',
    '15th-century Italy saw the formation of the two main variants that are known today.',
    'Other languages In most languages that use the Latin alphabet, denotes an open unrounded vowel, such as , , or .',
    'Both derive from the majuscule (capital) form.',
    'There was also a cursive style used for everyday or utilitarian writing, which was done on more perishable surfaces.',
    ', Alabama has the sixth highest poverty rate among states in the U.S.',
    'Alabama has made some changes since the late 20th century and has used new types of voting to increase representation.',
    'The northern part—along the Tennessee River Valley—is most vulnerable.',
    'A Literary History of Alabama: The Nineteenth Century (1979).',
    'Suburban Baldwin County, along the Gulf Coast, is the largest county in the state in both land area and water area.',
    'Spain held Mobile as part of Spanish West Florida until 1813.',
    'Construction began in 2013, with plans for it to become operable by 2015 and produce up to 50 aircraft per year by 2017.',
    'The largest single campus is the University of Alabama, located in Tuscaloosa, with 37,665 enrolled for fall 2016.',
    'Cahaba, now a ghost town, was the first permanent state capital from 1820 to 1825.',
    'I-22 enters the state from Mississippi and connects Birmingham with Memphis, Tennessee.',
    "Alabama's highest temperature of was recorded on September 5, 1925, in the unincorporated community of Centerville.",
    'Legion Field is home of the UAB Blazers football program and the Birmingham Bowl.',
    'The last remaining statewide Democrat, who served on the Alabama Public Service Commission, was defeated in 2012.',
    'This had caused decades of underinvestment in such areas.',
    'In the northern third of the state, there is a South Midland "arm" and "barb" rhyming with "form" and "orb".',
    'At the same time, many rural people migrated to the city of Birmingham to work in new industrial jobs.',
    'The current state constitution requires a voter referendum to raise property taxes.',
    'It had not changed legislative districts to reflect the decennial censuses, either.',
    'The 1901 constitution required racial segregation of public schools.',
    'This judicial authority was removed in April 2017.',
    'This did not change until the late 1960s following a lawsuit and court order.',
    'JVC America, Inc. operates an optical disc replication and packaging plant in Tuscaloosa.',
    "There has been a significant movement to rewrite and modernize Alabama's constitution.",
    "Alabama's government is divided into three coequal branches.",
    'The rate of school corporal punishment in Alabama is surpassed by only Mississippi and Arkansas.',
    'In FY 2006–2007, Alabama appropriated $3,775,163,578 for primary and secondary education.',
    "The eight models produced at the state's auto factories totaled combined sales of 74,335 vehicles for 2012.",
    "An 1842 article in the Jacksonville Republican proposed it meant 'Here We Rest'.",
    'Baháʼí centers in Alabama exist in Birmingham, Huntsville, and Florence.',
    'While part of the same large language family, the Muskogee tribes developed distinct cultures and languages.',
    'South Alabama reports many thunderstorms.',
    'The state has numerous place names of Native American origin.',
    'In another form of proportional representation, 23 jurisdictions use limited voting, as in Conecuh County.',
    'Through the legislative delegations, the Alabama legislature kept control of county governments.',
    'One example of this massive influx of workers occurred in Mobile.',
    'In a 2007 survey, nearly 70% of respondents could name all four of the Christian Gospels.',
    "The state's highest court is the Supreme Court of Alabama.",
    'In 1982, limited voting was first tested in Conecuh County.',
    'The numbers dropped even more in later decades.',
    'This compared to a nationwide seasonally adjusted rate of 5.4%.',
    'The British won the territory in 1763 until losing it in the American Revolutionary War.',
    'Local elections Many local offices (county commissioners, boards of education, tax assessors, tax collectors, etc.)',
    'A majority of people in the state identify as Evangelical Protestant.',
    "The state's other ports are on rivers with access to the Gulf of Mexico.",
    'In 2010, per capita income for the state was $22,984.',
    ', the state of Alabama has one female sheriff, in Morgan County, Alabama, and ten African-American sheriffs.',
    'Steel jobs, for instance, declined from 46,314 in 1950 to 14,185 in 2011.',
    'This second capitol building in Montgomery remains to the present day.',
    'Also, the Barber Motorsports Park has hosted IndyCar Series and Rolex Sports Car Series races.',
    'Peirce, Neal R. The Deep South States of America: People, Politics, and Power in the Seven Deep South States (1974).',
    'By 1903 only 2,980 African Americans were registered in Alabama, although at least 74,000 were literate.',
    'Experts in the Muskogean languages have not found any evidence to support such a translation.',
    'However, on October 29, 2019, U.S. District Judge Myron Thompson blocked the law from taking effect.',
    'During this time, urban interests and African Americans were markedly under-represented.',
    'The majority of Republican sheriffs have been elected in the more urban/suburban and heavily populated counties.',
    'Jackson, Harvey H. Inside Alabama: A Personal History of My State (2004).',
    'Alabama has no minimum wage and in February 2016 passed legislation preventing municipalities from setting one.',
    "From 1826 to 1846, Tuscaloosa served as Alabama's capital.",
    'Mobile is known for having the oldest organized Mardi Gras celebration in the United States, beginning in 1703.',
    "Greater Birmingham is Alabama's largest metropolitan area and its economic center.",
    'The state is usually ranked among the top in nation for its range of overall biodiversity.',
    'Additionally, Alabama has four National Forests: Conecuh, Talladega, Tuskegee, and William B. Bankhead.',
    'The suggestion that "Alabama" was borrowed from the Choctaw language is unlikely.',
    'Alabama has the highest per capita death penalty rate in the country.',
    'Its oldest city is Mobile, founded by French colonists in 1702 as the capital of French Louisiana.',
    'With a total of of inland waterways, Alabama has among the most of any state.',
    'The 2011 Super Outbreak produced a record amount of tornadoes in the state.',
    'U.S. farm-raised catfish is the 8th most popular seafood product in America.',
    'This area has attracted an influx of refugees from Cambodia, Laos, and Vietnam during the 1970s and thereafter.',
    'In 1984, under the Davis–Strong Act, the state legislature established the Alabama Indian Affairs Commission.',
    'Alabama is also prone to tropical storms and hurricanes.',
    'The single largest increase came in the area of information.',
    'It is headed by the governor of Alabama.',
    'The Goodyear Tire and Rubber Company operates a large plant in Gadsden which employs about 1,400 people.',
    "After the French lost to the British in the Seven Years' War, it became part of British West Florida from 1763 to 1783.",
    'The ATP Birmingham was a World Championship Tennis tournament held from 1973 to 1980.',
    'From July5 to August 2, 1819, delegates met to prepare the new state constitution.',
    'The area also drew many poor, disenfranchised people who became subsistence farmers.',
    'This is the Wetumpka crater, the site of "Alabama\'s greatest natural disaster".',
    'Public school funding is appropriated through the Alabama Legislature through the Education Trust Fund.',
    'Taxes Taxes are collected by the Alabama Department of Revenue.',
    'Jewish denominations in the state include two Orthodox, four Conservative, ten Reform, and one Humanistic synagogue.',
    'In the early 21st century, Republicans hold all seven of the statewide elected executive branch offices.',
    "Of the parks and natural destinations, Alabama's Gulf Coast topped the list with 6,700,000 visitors.",
    'Alabama: The History of a Deep South State (1994).',
    'PNC Financial Services and Wells Fargo also have a major presence in Alabama.',
    'The state was affected by the 1974 Super Outbreak and was devastated tremendously by the 2011 Super Outbreak.',
    'All sitting justices on the Alabama Supreme Court are members of the Republican Party.',
    'It was designed by Barachias Holt of Exeter, Maine.',
    'Generally, Alabama has very hot summers and mild winters with copious precipitation throughout the year.',
    'County and local governments Alabama has 67 counties.',
    'In a 2007 poll, 92% of Alabamians reported having at least some confidence in churches in the state.',
    'Alabama was under military rule from the end of the war in May 1865 until its official restoration to the Union in 1868.',
    "Alabama's capital is Montgomery, and its largest city by population and area is Huntsville.",
    'Factors that can cause lower life expectancy are maternal mortality, suicide, and gun crimes.',
    'After remaining an independent republic for a few days, it joined the Confederate States of America.',
    "Federal elections The state's two U.S. senators are Republican Richard C. Shelby and Republican Tommy Tuberville.",
    'They often donated land and labor as well.',
    'The company also operates terminals in Mobile, Melvin, and Moundville.',
    'The Legislature is responsible for writing, debating, passing, or defeating state legislation.',
    'Alabamians began to practice aquaculture in the early 1960s.',
    'It was formally recognized by the state legislature on January 25, 1844.',
    'Several of the surviving school buildings in the state are now listed on the National Register of Historic Places.',
    'This area was claimed by the French from 1702 to 1763 as part of La Louisiane.',
    'Alabama levies a 2%, 4%, or5% personal income tax, depending on the amount earned and filing status.',
    'Alabama is located in the middle of the Bible Belt, a region of numerous Protestant Christians.',
    'A super outbreak of 62 tornadoes hit the state in April 2011 and killed 238 people, devastating many communities.',
    'The current governor is Republican Kay Ivey.',
    'As early as 1702, the French called the tribe the , with French maps identifying the river as .',
    'In December 1819, Alabama was recognized as a state.',
    "A total of 387 schools, seven teachers' houses, and several vocational buildings were completed by 1937 in the state.",
    'The state ranges in elevation from sea level at Mobile Bay to more than in the northeast, to Mount Cheaha at .',
    'Since 1993, the automobile industry has generated more than 67,800 new jobs in the state.',
    'It also has limited executive authority in the county.',
    'The city was moved to the current site of Mobile in 1711.',
    'Since the 1980s judicial campaigns have become increasingly politicized.',
    'Each county has its own elected legislative branch, usually called the county commission.',
    'It was among the most destructive storms to strike the state in its modern history.',
    'During the 1960s, under Governor George Wallace, Alabama resisted compliance with federal demands for desegregation.',
    'Jordan-Hare Stadium is the home field of the Auburn football team and seats up to 87,451.',
    'The current chief justice of the Alabama Supreme Court is Republican Tom Parker.',
    'By 1920, Birmingham was the 36th-largest city in the United States.',
    'Invertebrates include 97 crayfish species and 383 mollusk species.',
    "The state's seasonally adjusted unemployment rate was 5.8% in April 2015.",
    "More than 160 years later, the French founded the region's first European settlement at Old Mobile in 1702.",
    'The Port of Mobile was ranked 12th by tons of traffic in the United States during 2009.',
    'That represented an increase of $444,736,387 over the previous fiscal year.',
    'It was claimed by the Province of Georgia from 1767 onwards.',
    'The executive branch is responsible for the execution and oversight of laws.',
    'The fund required the local community and state to raise matching funds to pay the rest.',
    'On January 11, 1861, Alabama declared its secession from the Union.',
    "During and after World War II, Alabama grew as the state's economy diversified with new industries.",
    'Climate The state is classified as humid subtropical (Cfa) under the Koppen Climate Classification.',
    'The members of the Legislature take office immediately after the November elections.',
    'However, there are no correspondingly similar words in the Alabama language.',
    'Most monastic Buddhist temples are concentrated in southern Mobile County, near Bayou La Batre.',
    'The current split is 35 Democrats, 31 Republicans, and one Independent Fayette.',
    'Part of the frontier in the 1820s and 1830s, its constitution provided for universal suffrage for white men.',
    'Construction Brasfield & Gorrie, BE&K, Hoar Construction, and B.L.',
    "Historic snowfall events include New Year's Eve 1963 snowstorm and the 1993 Storm of the Century.",
    'Until 1994, no Republicans held any of the court seats.',
    ', there are a total of 3,589,839 registered voters, with 3,518,285 active, and the others inactive in the state.',
    'Only Alabama, Mississippi, and South Dakota tax groceries at the full state sales tax rate.',
    'Alabama is also known as the "Heart of Dixie" and the "Cotton State".',
    'There are six Dharma centers and organizations for Theravada Buddhists.',
    "In 2011, 46.6% of Alabama's population younger than age1 were minorities.",
    "The state's general sales tax rate is 4%.",
    'Legislative delegations retain certain powers over each county.',
    'Other changes were made to implement representative state house and senate districts.',
    'Media Major newspapers include Birmingham News, Mobile Press-Register, and Montgomery Advertiser.',
    'Alabama has coastline at the Gulf of Mexico, in the extreme southern edge of the state.',
    'Property taxes of .40% of assessed value per year, are the second-lowest in the U.S., after Hawaii.',
    "The assembly plant is the company's first factory to be built within the United States.",
    'Notes The Talladega Superspeedway motorsports complex hosts a series of NASCAR events.',
    'At-large voting had diluted the votes of any minority in a county, as the majority tended to take all seats.',
    'It currently ranks fifth in the nation for the diversity of its flora.',
    'These counties include Dallas, Lowndes, Marengo and Perry."',
    'The company wore new uniforms with yellow trim on the sleeves, collar and coattails.',
    'The peak season for tornadoes varies from the northern to southern parts of the state.',
    'Other spellings of the name have included Alibamu, Alabamo, Albama, Alebamon, Alibama, Alibamou, Alabamu, Allibamou.',
    'However, most of the Democratic sheriffs preside over rural and less populated counties.',
    'The Alabama Alcoholic Beverage Control Board controls the sale and distribution of alcoholic beverages in the state.',
    'In July 2013, the plant was sold to ArcelorMittal and Nippon Steel.',
    '"Latinization in the Heart of Dixie: Hispanics in Late-twentieth-century Alabama" Alabama Review (2002, 55(4): 243–274).',
    'The monument was removed in August 2003.',
    'In 2010, Republicans won control of both houses of the legislature for the first time in 136 years.',
    'Alabama in the Twentieth Century (2004).',
    'Birmingham experienced such rapid growth it was called the "Magic City".',
    'Beginning in 1913, the first 80 Rosenwald Schools were built in Alabama for African-American children.',
    'Republicans hold six of the eight elected seats on the Alabama State Board of Education.',
    'By 2006, crop and animal production in Alabama was valued at $1.5billion.',
    'Muslims have been increasing in Alabama, with 31 mosques built by 2011, many by African-American converts.',
    'in the state are still held by Democrats.',
    'It is home to nearly 4,000 pteridophyte and spermatophyte plant species.',
    'A few natural disasters have occurred in the state in the twenty-first century.',
    'Cotton and other cash crops faded in importance as the state developed a manufacturing and service base.',
    'Banking Regions Financial Corporation is the largest bank headquartered in or operating in Alabama.',
    'Aquaculture Aquaculture is a large part of the economy of Alabama.',
    'Elections In a 2020 study, Alabama was ranked as the 12th most difficult state for citizens to vote.',
    'The first structure burned down in 1849, but was rebuilt on the same site in 1851.',
    'Tourism and entertainment According to Business Insider, Alabama ranked 14th in most popular states to visit in 2014.',
    'Alabama currently ranks 4th in the nation for vehicle exports.',
    "The word's spelling varies significantly among historical sources.",
    'A -wide meteorite hit the area about 80 million years ago.',
    "Alabama's slaves were freed by the 13th Amendment in 1865.",
    'Railroad passenger cars were segregated in 1891.',
    'Since the mid- to late 20th century, however, white conservatives started shifting to the Republican Party.',
    'Alabama was heavily involved in the American Civil War.',
    'Following the Revolutionary War, it remained a part of Georgia, although heavily disputed.',
    'However, executions per capita are significantly higher in Texas.',
    'Since a direct connection from I-22 to I-422 will not be possible, I-222 has been proposed, as well.',
    'The record low of occurred on January 30, 1966, in New Market.',
    'Huntsville served as temporary capital from 1819 to 1820, when the seat of government moved to Cahaba in Dallas County.',
    'The corporate income tax rate in Alabama is 6.5%.',
    'The first legislative session in the new capital met in December 1847.',
    'A -wide meteorite impact crater is located in Elmore County, just north of Montgomery.',
    'This has resulted in more proportional representation for voters.',
    'They held on to old representation to maintain political and economic power in agricultural areas.',
    'This compared to more than 181,000 African Americans eligible to vote in 1900.',
    'UAB is the largest state government employer in Alabama, with a workforce of about 18,000.',
    'Automakers accounted for approximately a third of the industrial expansion in the state in 2012.',
    'Heavy industry and mining were the basis of its economy.',
    'Alabama is the 30th largest by area and the 24th-most populous of the U.S. states.',
    "In 2020, Alabama produced ⅓ of the United States' farm-raised catfish.",
    'Alabama is nicknamed the Yellowhammer State, after the state bird.',
    'The average annual temperature is 64°F (18°C).',
    'By 1941 more Whites than Blacks had been disenfranchised: 600,000 to 520,000.',
    'Mardi Gras is an official state holiday in Mobile and Baldwin counties.',
    'The Assemblies of God had almost 60,000 members, the Churches of Christ had nearly 120,000 members.',
    'The state tree is the longleaf pine, and the state flower is the camellia.',
    'A sixth route, I-685, will be formed when I-85 is rerouted along a new southern bypass of Montgomery.',
    'During the antebellum period, Alabama was a major producer of cotton, and widely used African American slave labor.',
    'Until 1964, the state elected state senators on a geographic basis by county, with one per county.',
    'In the southern Gulf coast, snowfall is less frequent, sometimes going several years without any snowfall.',
    'The same year, legislation was approved that called for racially segregated schools.',
    'The center of population of Alabama is located in Chilton County, outside the town of Jemison.',
    'In 2004, Hurricane Ivan, a category 3 storm upon landfall, struck the state and caused over $18 billion of damage.',
    'The plans include a $600million factory at the Brookley Aeroplex for the assembly of the A319, A320 and A321 aircraft.',
    'Owen Thomas M. History of Alabama and Dictionary of Alabama Biography (4 vols, 1921).',
    'The United States Congress created the Alabama Territory on March 3, 1817.',
    "Alabama's 2012 GDP increased 1.2% from the previous year.",
    'He settled in the Tombigbee District during the early 1770s.',
    'A proposed northern bypass of Birmingham will be designated as I-422.',
    "Alabama's land consists of of forest or 67% of the state's total land area.",
    'The annual average snowfall for the Birmingham area is per year.',
    'Urban interests were consistently underrepresented in the legislature.',
    'Rural workers poured into the largest cities in the state for better jobs and a higher standard of living.',
    'Some critics believe the election of judges has contributed to an exceedingly high rate of executions.',
    'Alabama uses partisan elections to select judges.',
    'The Republican Party currently holds a majority in both houses of the Legislature.',
    'Later immigrants in the nineteenth and twentieth centuries tended to be Ashkenazi Jews from eastern Europe.',
    'The largest educational gains were among people with some college education but without degrees.',
    'The Gulf Coast, around Mobile Bay, averages between 70 and 80 days per year with thunder reported.',
    'The expedition of Hernando de Soto passed through Mabila and other parts of the state in 1540.',
    'Organized insurgent, resistance groups tried to suppress the freedmen and Republicans.',
    'The Yazoo lands were added to the territory in 1804, following the Yazoo land scandal.',
    'Between 1940 and 1943, more than 89,000 people moved into the city to work for war-related industries.',
    'Provisions which disenfranchised blacks resulted in excluding many poor Whites.',
    'Nearly all Blacks had lost the ability to vote.',
    'St. Stephens, now abandoned, served as the territorial capital from 1817 to 1819.',
    'A new capitol building was erected under the direction of Stephen Decatur Button of Philadelphia.',
    'Wells Fargo has a regional headquarters, an operations center campus, and a $400million data center in Birmingham.',
    'Following the war, the state remained chiefly agricultural, with an economy tied to cotton.',
    'In some years, it imposes more death sentences than does Texas, a state which has a population five times larger.',
    'The composition of other traditions is 0.5% Mormon, 0.5% Jewish, 0.5% Muslim, 0.5% Buddhist, and 0.5% Hindu.',
    'This notion was popularized in the 1850s through the writings of Alexander Beaufort Meek.',
    "The oldest Jewish congregation in the state is Congregation Sha'arai Shomayim in Mobile.",
    'In 2020, sales and excise taxes in Alabama accounted for 38% of all state and local revenue.',
    '113 of these mollusk species have never been collected outside the state.',
    "The Confederacy's capital was initially at Montgomery.",
    'Together, 1,496 individual schools provide education for 744,637 elementary and secondary students.',
    'Alabama is an alcoholic beverage control state, meaning the state government holds a monopoly on the sale of alcohol.',
    '(A Birmingham city ordinance would have raised theirs to $10.10.)',
    'created a statue group Achilles and Penthesilea (1895; Vienna).',
    'The whole expression would be comparable to the Latin acupedius "swift of foot".',
    'Achille et Déidamie (Paris 1735) is an opera composed by André Campra.',
    'Some retellings also state that Achilles was scaling the gates of Troy and was hit with a poisoned arrow.',
    'It is not clear if this version of events was known earlier.',
    'Achilles refused, claiming to have no medical knowledge.',
    "Hélène Monsacré (1984), Les larmes d'Achille.",
    "In the Iliad Homer's Iliad is the most famous narrative of Achilles' deeds in the Trojan War.",
    'Achilles then kills Hector and drags his corpse by its heels behind his chariot.',
    'While the women fled in panic, Achilles prepared to defend the court, thus giving his identity away.',
    'Achilles Come Down is a song on the 2017 Gang of Youths album Go Farther in Lightness.',
    'Achille à Scyros (Paris 1804) is a ballet by Pierre Gardel, composed by Luigi Cherubini.',
    'When Penthesilea, queen of the Amazons and daughter of Ares, arrives in Troy, Priam hopes that she will defeat Achilles.',
    'The poem is in part about the misdirection of anger on the part of leadership.',
    'Plato In Hippias Minor, a dialogue attributed to Plato, an arrogant man named Hippias argues with Socrates.',
    'Zeus was furious and decreed that she would never marry an immortal.',
    'A number of important commercial port cities of the Greek waters were dedicated to Achilles.',
    'Despite his youth, he was one of the main Trojan war leaders, a "horse fighter" or "chariot fighter" according to Homer.',
    "In Book 11 of Homer's Odyssey, Odysseus sails to the underworld and converses with the shades.",
    'Achilles auf Skyros (Stuttgart 1926) is a ballet by the Austrian-British composer and musicologist Egon Wellesz.',
    'Ancient writers treated Troilus as the epitome of a dead child mourned by his parents.',
    'In the Iliad, it appears to be the model of a deep and loyal friendship.',
    'Anthony Edwards (1985a), "Achilles in the Underworld: Iliad, Odyssey, and Æthiopis".',
    'Furthermore, laós has been construed by Gregory Nagy, following Leonard Palmer, to mean "a corps of soldiers", a muster.',
    'Some researchers deem the name a loan word, possibly from a Pre-Greek language.',
    'Agamemnon refuses, and Apollo sends a plague amongst the Greeks.',
    "Achilles' wrath (μῆνις Ἀχιλλέως, mênis Achilléōs) is the central theme of the poem.",
    'Homer does not suggest that Achilles and his close friend Patroclus had sexual relations.',
    'This leaves the reader with an ambiguous understanding of how Achilles felt about the heroic life.',
    '(2016), Themes of the Trojan Cycle: Contribution to the study of the greek mythological tradition (Coimbra).',
    'Achilleus (1908) is a lithography by Max Slevogt.',
    'His mother Thetis comes to comfort the distraught Achilles.',
    'Anthony Edwards (1985b), "Achilles in the Odyssey: Ideologies of Heroism in the Homeric Epic".',
    "In another version of the story, Odysseus arranged for a trumpet alarm to be sounded while he was with Lycomedes' women.",
    'Ann Arbor, Michigan: University Microfilms International.',
    'According to Homer, Achilles grew up in Phthia with his companion Patroclus.',
    '(To the "Race-course" he gives a length of 80 miles, c. 120 km, whereas the spit measures c. 70 km today.)',
    'In this island there is also Achilles\' temple and his statue".',
    'Operas titled Deidamia were composed by Francesco Cavalli (1644) and George Frideric Handel (1739).',
    'Extant fragments of the Achilleis and other Aeschylean fragments have been assembled to produce a workable modern play.',
    "Achilles is a major supporting character in David Gemmell's Troy series of books (2005–2007).",
    'Birth and early years Achilles was the son of the Thetis, a nereid, and Peleus, the king of the Myrmidons.',
    'Pieces of the spear were scraped off onto the wound and Telephus was healed.',
    'Jonathan S. Burgess (2009), The Death and Afterlife of Achilles.',
    'Achilles appears in the light novel series Fate/Apocrypha (2012–2014) as the Rider of Red.',
    "Achilles is one of various 'narrators' in Colleen McCullough's novel The Song of Troy (1998).",
    'Its paintings and statuary depict scenes from the Trojan War, with particular focus on Achilles.',
    'He appointed five leaders (each leader commanding 500 Myrmidons): Menesthius, Eudorus, Peisander, Phoenix and Alcimedon.',
    'The tragedian Sophocles also wrote The Lovers of Achilles, a play with Achilles as the main character.',
    'The 1983 novel Kassandra by Christa Wolf also treats the death of Achilles.',
    'The building is named the Achilleion, after Achilles.',
    'After his temporary truce with Priam, Achilles fights and kills the warrior queen, only to grieve over her death later.',
    'The kings of Epirus claimed to be descended from Achilles through his son, Neoptolemus.',
    'She was interrupted by Peleus and abandoned both father and son in a rage.',
    'Other battle honours include Walcheren 1809.',
    'A species of lizard, Anolis achilles, which has widened heel plates, is named for Achilles.',
    'They were absorbed in the game and oblivious to the surrounding battle.',
    'Consequently, Eos will not let the sun rise until Zeus persuades her.',
    'It has also been set to music as Il Trionfo della gloria.',
    "After death, Achilles' bones were mingled with those of Patroclus, and funeral games were held.",
    'Achille (Vienna 1801) is an opera by Ferdinando Paër on a libretto by Giovanni de Gamerra.',
    'Graves, Robert, The Greek Myths, Harmondsworth, London, England, Penguin Books, 1960.',
    'He is said to have visited the tomb of Achilles at Achilleion while passing Troy.',
    "In the few fragmentary poems of the Epic Cycle which describe the hero's death (i.e.",
    'He was ambidextrous, and cast a spear from each hand; one grazed Achilles\' elbow, "drawing a spurt of blood".',
    'After Hector realizes the trick, he knows the battle is inevitable.',
    'As a student of the monist Parmenides and a member of the Eleatic school, Zeno believed time and motion to be illusions.',
    'Baltimore: Johns Hopkins University Press.',
    'The god tries to drown Achilles but is stopped by Hera and Hephaestus.',
    'Dale S. Sinos (1991), The Entry of Achilles into Greek Epic, PhD thesis, Johns Hopkins University.',
    "Following the death of Patroclus, Nestor's son Antilochus becomes Achilles' closest companion.",
    "In some versions, the god Apollo guided Paris' arrow.",
    "Achilles is a main character in Terence Hawkins' 2009 novel The Rage of Achilles.",
    'He was the son of the Nereid Thetis and Peleus, king of Phthia.',
    'Agamemnon agrees and sends Odysseus and two other chieftains, Ajax and Phoenix.',
    'The Trojans attacked and reached the heroes, who were saved only by an intervention of Athena.',
    'The grief or distress of the people is a theme raised numerous times in the Iliad (and frequently by Achilles himself).',
    'None of the sources before Statius make any reference to this general invulnerability.',
    'An even earlier composition is from Antonio Caldara (Vienna 1736).',
    'Socrates uses various analogies, discussing athletics and the sciences to prove his point.',
    "Later versions of the story suggested Troilus was accidentally killed by Achilles in an over-ardent lovers' embrace.",
    'He warns Percy Jackson about the Curse of Achilles and its side effects.',
    'Achilles, Agony and Ecstasy in Eight Parts is the first song on the 1992 Manowar album The Triumph of Steel.',
    'Once he realized that his distraction was endangering his life, he refocused and killed her.',
    "Achilles is one of the main characters in Dan Simmons's novels Ilium (2003) and Olympos (2005).",
    'The two argue over whether it is better to lie on purpose or by accident.',
    'Pausanias reports that the Delphic Pythia sent a lord of Croton to be cured of a chest wound.',
    "Similarly, others relate the island's name to its white cliffs, snakes or birds dwelling there.",
    'An armored cruiser of that name served in the Royal Navy during the First World War.',
    'The Rage of Achilles is a fresco by Giovanni Battista Tiepolo (1757, Villa Valmarana Ai Nani, Vicenza).',
    "Achilles' most notable feat during the Trojan War was the slaying of the Trojan prince Hector outside the gates of Troy.",
    'The Aethiopis is now lost, except for scattered fragments quoted by later authors.',
    'Gregory Nagy (1999), The Best of The Acheans: Concepts of the Hero in Archaic Greek Poetry.',
    'The Trojans, led by Hector, subsequently push the Greek army back toward the beaches and assault the Greek ships.',
    "Prophecies linked Troilus' fate to that of Troy and so he was ambushed in an attempt to capture him.",
    "Akhilles is killed by a poisoned Kentaur arrow shot by Kassandra in Marion Zimmer Bradley's novel The Firebrand (1987).",
    'The shift from -dd- to -ll- is then ascribed to the passing of the name into Greek via a Pre-Greek source.',
    'Achilles chose the former, and decided to take part in the Trojan War.',
    'Johns Hopkins University Press (revised edition, online).',
    'A second exploration in 1840 showed that the construction of a lighthouse had destroyed all traces of this temple.',
    "The poem ends with a description of Hector's funeral, with the doom of Troy and Achilles himself still to come.",
    'The two get into a discussion about lying.',
    'Achilles is the subject of the poem Achilleis (1799), a fragment by Johann Wolfgang von Goethe.',
    "Alternatively, Telephus held Orestes for ransom, the ransom being Achilles' aid in healing the wound.",
    "He is seen in Hell's second circle, that of lust.",
    'The novel explores the relationship between Patroclus and Achilles from boyhood to the fateful events of the Iliad.',
    'Odysseus eventually gave the armour to Neoptolemus, the son of Achilles.',
    'Achilles rejects all Agamemnon offers him and simply urges the Greeks to sail home as he was planning to do.',
    'It became famous for its part in the Battle of the River Plate, alongside and .',
    'Peleus entrusted Achilles to Chiron the Centaur, who lived on Mount Pelion, to be reared.',
    'Many pairs of men throughout history have been compared to Achilles and Patroclus to imply a homosexual relationship.',
    "Achilles is the main character in David Malouf's novel Ransom (2009).",
    'was a which served with the Royal New Zealand Navy in World War II.',
    "In modern literature and arts Literature Achilles appears in Dante's Inferno (composed 1308–1320).",
    'Telephus When the Greeks left for the Trojan War, they accidentally stopped in Mysia, ruled by King Telephus.',
    'Leuce had also a reputation as a place of healing.',
    'Achille et Polyxène (Paris 1687) is an opera begun by Jean-Baptiste Lully and finished by Pascal Collasse.',
    'Wanting to go down fighting, he charges at Achilles with his only weapon, his sword, but misses.',
    "The French dramatist Thomas Corneille wrote a tragedy La Mort d'Achille (1673).",
    'At first, he was so distracted by her beauty, he did not fight as intensely as usual.',
    "Achilles asks Priam for Polyxena's hand in marriage.",
    'In 1921, Edward Shanks published The Island of Youth and Other Poems, concerned among others with Achilles.',
    "Gregory Nagy (1984), The Name of Achilles: Questions of Etymology and 'Folk Etymology, Illinois Classical Studies.",
    'In the later vase paintings presenting the death of Achilles, the arrow (or in many cases, arrows) hit his torso.',
    'Pausanias has been told that the island is "covered with forests and full of animals, some wild, some tame.',
    'Gallery References Further reading Ileana Chirassi Colombo (1977), "Heroes Achilleus – Theos Apollon."',
    'Achilles, like Odysseus, told numerous falsehoods.',
    'The new armour includes the Shield of Achilles, described in great detail in the poem.',
    'In 5th-century BCE Athens, the intense bond was often viewed in light of the Greek custom of paiderasteia.',
    "Another version of Achilles' death is that he fell deeply in love with one of the Trojan princesses, Polyxena.",
    'The two also reference Homer extensively.',
    'The Achilles tendon is also named after him due to these legends.',
    "Priam is willing because it would mean the end of the war and an alliance with the world's greatest warrior.",
    'Ammianus Marcellinus attributes the healing to waters (aquae) on the island.',
    'Music Achilles has been frequently the subject of operas, ballets and related genres.',
    'In the Trojan War According to the Iliad, Achilles arrived at Troy with 50 ships, each carrying 50 Myrmidons.',
    'Her father Chryses, a priest of Apollo, begs Agamemnon to return her to him.',
    "Achilles' Wrath is a concert piece by Sean O'Loughlin.",
    'They promise that, if Achilles returns to battle, Agamemnon will return the captive Briseis and other gifts.',
    'He was represented in the Aethiopis as living after his death in the island of Leuke at the mouth of the river Danube.',
    "The ghost of Achilles appears in Rick Riordan's The Last Olympian (2009).",
    "Le héros, la femme et la souffrance dans la poésie d'Homère, Paris: Albin Michel.",
    'Odysseus reasoned that the spear had inflicted the wound; therefore, the spear must be able to heal it.',
    "In this version of the myth, Achilles' death therefore came in retribution for this sacrilege.",
    'At some point in the war, Achilles and Ajax were playing a board game (petteia).',
    'Paris was later killed by Philoctetes using the enormous bow of Heracles.',
    'Achilles was cremated and his ashes buried in the same urn as those of Patroclus.',
    'Agamemnon has taken a woman named Chryseis as his slave.',
    'For this reason, the two gods withdrew their pursuit, and had her wed Peleus.',
    'Graves, Robert, The Greek Myths: The Complete and Definitive Edition.',
    'Achilles does so, and Calchas declares that Chryseis must be returned to her father.',
    'Achilles Last Stand a track on the 1976 Led Zeppelin album Presence.',
    'Accepting his fate, Hector begs Achilles not to spare his life, but to treat his body with respect after killing him.',
    'After a brief interview, Stanton declared him a patriot and dismissed the charge.',
    'Lincoln briefly interrupted his campaign to serve as a captain in the Illinois Militia during the Black Hawk War.',
    'With ratification, it became the Thirteenth Amendment to the United States Constitution on December 6, 1865.',
    'Lincoln made five appointments to the Supreme Court.',
    'One Illinois newspaper derisively nicknamed him "spotty Lincoln".',
    'In 1844, the couple bought a house in Springfield near his law office.',
    'The Civil War was a significant force in the eventual dominance of the singular usage by the end of the 19th century.',
    'En route to his inauguration, Lincoln addressed crowds and legislatures across the North.',
    'The United States Navy is named after Lincoln, the second Navy ship to bear his name.',
    'As a result, Union enlistments from Maryland, Kentucky, and Missouri increased by over 40,000.',
    "McClellan's slow progress frustrated Lincoln, as did his position that no troops were needed to defend Washington.",
    'Lincoln persisted with the policy of suspension in select areas.',
    "Lincoln's argument assumed a moral tone, as he claimed Douglas represented a conspiracy to promote slavery.",
    'In 1865, Lincoln was asked how he came to acquire his rhetorical skills.',
    "Ford's Theatre, among the top sites in Washington, D.C., is across the street from Petersen House (where he died).",
    'Enlisting former slaves became official policy.',
    'Hooker was routed by Lee at the Battle of Chancellorsville in May, then resigned and was replaced by George Meade.',
    "Lincoln's body was buried at Oak Ridge Cemetery in Springfield and now lies within the Lincoln Tomb.",
    'Nevada, which became the third state in the far-west of the continent, was admitted as a free state on October 31, 1864.',
    'Lincoln instructed his backers to vote for Lyman Trumbull.',
    'He suggested that postmodernism and multiculturalism have diluted greatness as a concept.',
    'Lincoln refused to negotiate with the Confederacy as a coequal; his objective to end the fighting was not realized.',
    'Bennett argued that Lincoln opposed social equality, and proposed sending freed slaves to another country.',
    'Gettysburg Address (1863) Lincoln spoke at the dedication of the Gettysburg battlefield cemetery on November 19, 1863.',
    'The deaths of their sons, Eddie and Willie, had profound effects on both parents.',
    'A group of former Whigs and Know Nothings formed the Constitutional Union Party and nominated John Bell of Tennessee.',
    'He elevated Henry Halleck in July and appointed John Pope as head of the new Army of Virginia.',
    'On April 12, 1861, Confederate forces fired on Union troops at Fort Sumter and began the fight.',
    'As Southern states fell, they needed leaders while their administrations were restored.',
    'He was private about his position on organized religion and respected the beliefs of others.',
    'His Gettysburg Address appealed to nationalistic, republican, egalitarian, libertarian, and democratic sentiments.',
    'Lincoln later regretted some of his statements, especially his attack on presidential war-making powers.',
    "Privately, Lincoln concluded that the Confederacy's slave base had to be eliminated.",
    'While Lincoln was popular in the Midwest, he lacked support in the Northeast and was unsure whether to seek office.',
    'The idea was never commercialized, but it made Lincoln the only president to hold a patent.',
    'The administration offered to appoint him secretary or governor of the Oregon Territory as consolation.',
    'He made his home in New Salem, Illinois, for six years.',
    'By October 9, Pope considered the uprising to be ended; hostilities ceased on December 26.',
    'Thomas and Nancy married on June 12, 1806, in Washington County, and moved to Elizabethtown, Kentucky.',
    'Over the coming months, Lincoln was tireless, making nearly fifty speeches along the campaign trail.',
    'Ten years later, on January 20, 1828, Sarah died while giving birth to a stillborn son, devastating Lincoln.',
    'However, despite his overwhelming support in the Midwestern United States, he was less appreciated in the east.',
    'He worked more often and more closely with Lincoln than any other senior official.',
    'Lincoln suspended the writ of habeas corpus where needed for the security of troops trying to reach Washington.',
    'Then followed his four terms in the Illinois House of Representatives for Sangamon County.',
    'He faced difficulties guarding Western settlers, railroads, and telegraphs, from Indian attacks.',
    "Democratic opponents accused Lincoln of using the military to ensure his and the Republicans' political aspirations.",
    'Secession sentiment was strong in Missouri and Maryland, but did not prevail; Kentucky remained neutral.',
    "Several claims have been made that Lincoln's health was declining before the assassination.",
    'Meanwhile, Lincoln emboldened Grant with more troops and Republican party support.',
    'The successful reunification of the states had consequences for how people viewed the country.',
    'On November 6, 1860, Lincoln was elected the 16th president.',
    'By the quality and simplicity of his rhetoric, he quickly became the champion of the Republican party.',
    'Thanksgiving had become a regional holiday in New England in the 17th century.',
    'Responding to criticism of Grant after Shiloh, Lincoln had said, "I can\'t spare this man.',
    'Lincoln sought to be lenient, but still send a message.',
    'Pope fought against the Indians mercilessly, even advocating their extinction.',
    'They had three children: Sarah, Abraham, and Thomas, who died as infant.',
    'He did this at a time when the Constitution, which "tolerated slavery", was the focus of most political discourse.',
    "Marriage and children Lincoln's first romantic interest was Ann Rutledge, whom he met when he moved to New Salem.",
    'While anxiously preparing for the nuptials, he was asked where he was going and replied, "To hell, I suppose."',
    'In 1816, the family moved to Indiana where the land surveys and titles were more reliable.',
    'Lincoln ordered thousands of Confederate prisoners of war sent by railroad to put down the Dakota Uprising.',
    'President Johnson was sworn in the next morning.',
    'The law opened land for a lease of three years with the ability to purchase title for the freedmen.',
    "Lincoln presided over the expansion of the federal government's economic influence in other areas.",
    'Lincoln emphasized his opposition to Polk by drafting and introducing his Spot Resolutions.',
    'On February 23, 1861, he arrived in disguise in Washington, D.C., which was placed under substantial military guard.',
    'Meanwhile, Lincoln and the Republican leadership agreed that the dismantling of the Union could not be tolerated.',
    'He took blue mass pills, which contained mercury, to treat constipation.',
    'By the spring of 1863, Lincoln was ready to recruit black troops in more than token numbers.',
    'Many others gathered along the tracks as the train passed with bands, bonfires, and hymn singing or in silent grief.',
    'Grant in 1864 waged the bloody Overland Campaign, which exacted heavy losses on both sides.',
    'On April 9, Lee surrendered to Grant at Appomattox, officially ending the war.',
    'When a general asked Lincoln how the defeated Confederates were to be treated, Lincoln replied, "Let \'em up easy."',
    'His allies, the War Democrats and the Radical Republicans, demanded harsh treatment of the Southern Confederates.',
    'The law had little practical effect, but it signaled political support for abolishing slavery.',
    'Lincoln ran for President in 1860, sweeping the North in victory.',
    'Although the economy was booming, the business struggled and Lincoln eventually sold his share.',
    "African Americans were especially moved; they had lost 'their Moses'.",
    'Bennett won wide attention when he called Lincoln a white supremacist in 1968.',
    'Then I had no right to deprive the country of their services."',
    'His nomination was confirmed by the Senate on March 2, 1864.',
    'The principals stood in stark contrast both physically and politically.',
    'He was the first of five presidents to do so.',
    'The failure of the Peace Conference of 1861 signaled that legislative compromise was impossible.',
    'On the day Lincoln was assassinated, he reportedly told his wife he desired to visit the Holy Land.',
    'The oldest, Robert Todd Lincoln, was born in 1843 and was the only child to live to maturity.',
    'Lincoln was an affectionate husband and father of four sons, though his work regularly kept him away from home.',
    'He ordered Indian farms and food supplies be destroyed, and Indian warriors be killed.',
    'Many in the audience thought he appeared awkward and even ugly.',
    'The Fort Sumter attack rallied Americans north of the Mason-Dixon line to defend the nation.',
    'He said the Kansas Act had a "declared indifference, but as I must think, a covert real zeal for the spread of slavery.',
    'The speech created a stark image of the danger of disunion.',
    'He dropped the bill when it eluded Whig support.',
    'It is unknown to what extent he may have suffered from mercury poisoning.',
    "Grant then assumed command of Meade's army.",
    "His children, including eight-year-old Thomas, Abraham's father, witnessed the attack.",
    'Michael Martinez wrote about the effective imaging of Lincoln by his campaign.',
    'Lincoln had pledged in 1846 to serve only one term in the House.',
    'The Confederate government evacuated Richmond and Lincoln visited the conquered capital.',
    'He also faced significant public pressure, including threats of mob justice should any of the Dakota be spared.',
    'Though he did not give public appearances, many sought to visit him and write him.',
    'Lincoln and some friends took goods by flatboat to New Orleans, Louisiana, where he was first exposed to slavery.',
    'Lincoln did not note what his children were doing or had done."',
    "In it, he deemed the war casualties to be God's will.",
    'It will become all one thing, or all the other."',
    'In response to an inquiry about his ambitions, Lincoln said, "The taste is in my mouth a little."',
    'Owens arrived that November and he courted her for a time; however, they both had second thoughts.',
    'His likeness also appears on many postage stamps.',
    "Lincoln's appointments were designed to harness both moderates and Radicals.",
    'It had been sporadically proclaimed by the federal government on irregular dates.',
    'The Senate campaign featured seven debates between Lincoln and Douglas.',
    "In 1862, Lincoln removed McClellan for the general's continued inaction.",
    'At that time, senators were elected by the state legislature.',
    "Pope satisfied Lincoln's desire to advance on Richmond from the north, thus protecting Washington from counterattack.",
    'Many Illinois Republicans resented this eastern interference.',
    'He persisted as an avid reader and retained a lifelong interest in learning.',
    'Lincoln and Douglas competed for votes in the North, while Bell and Breckinridge primarily found support in the South.',
    'He has been memorialized in many town, city, and county names, including the capital of Nebraska.',
    'In 1862, Congress created the Department of Agriculture.',
    'I do not expect the Union to be dissolved—I do not expect the house to fall—but I do expect it will cease to be divided.',
    'Religious and philosophical beliefs As a young man, Lincoln was a religious skeptic.',
    'Lincoln argued that slavery would be rendered obsolete if its expansion into new territories were prevented.',
    'His family even said he was lazy, for all his "reading, scribbling, writing, ciphering, writing Poetry, etc.".',
    'After Scott was returned to the slave state he petitioned a federal court for his freedom.',
    'From 1853 to 1860, one of his largest clients was the Illinois Central Railroad.',
    'His victory in the electoral college was decisive: Lincoln had 180 votes to 123 for his opponents.',
    'Historians agree that it is impossible to predict exactly how Reconstruction would have proceeded had Lincoln lived.',
    'Confederate Vice President Stephens led a group meeting with Lincoln, Seward, and others at Hampton Roads.',
    'These are often based on photographs of Lincoln appearing to show weight loss and muscle wasting.',
    'And having begun, He could give the final victory to either side any day.',
    "Lincoln traveled to Grant's headquarters at City Point, Virginia, to confer with Grant and William Tecumseh Sherman.",
    'Lincoln began to appreciate the critical need to control strategic points, such as the Mississippi River.',
    'He suspended habeas corpus in Maryland, and he averted British intervention by defusing the Trent Affair.',
    "Reunification of the states In Lincoln's first inaugural address, he explored the nature of democracy.",
    'He later said of his legal education that "I studied with nobody."',
    'Lincoln canceled the illegal proclamation as politically motivated and lacking military necessity.',
    'Instead of focusing on the legality of an argument, he focused on the moral basis of republicanism.',
    'His stepmother acknowledged he did not enjoy "physical labor", but loved to read.',
    "The National Union Party was united by Lincoln's support for emancipation.",
    'Therefore we must take a man whose opinions are known."',
    'We needed to hold our own people together.',
    "Lincoln's guest Major Henry Rathbone momentarily grappled with Booth, but Booth stabbed him and escaped.",
    'Noah Haynes Swayne was an anti-slavery lawyer who was committed to the Union.',
    'In June 1862, Congress passed an act banning slavery on all federal territory, which Lincoln signed.',
    'By March 1861, no leaders of the insurrection had proposed rejoining the Union on any terms.',
    'He wrote at this time that God "could have either saved or destroyed the Union without a human contest.',
    'Twice a week, Lincoln met with his cabinet in the afternoon.',
    'He sought to heal the war-torn nation through reconciliation.',
    "Pennsylvania put him over the top, led by the state's iron interests who were reassured by his tariff support.",
    'President Buchanan and President-elect Lincoln refused to recognize the Confederacy, declaring secession illegal.',
    'The Radicals retaliated by refusing to seat elected representatives from Louisiana, Arkansas, and Tennessee.',
    'Lincoln gained the support of Congress and the northern public for these actions.',
    'Abraham became close to his stepmother and called her "Mother".',
    'The 1862 Homestead Act made millions of acres of Western government-held land available for purchase at low cost.',
    'North Carolina, Tennessee, and Arkansas followed over the following two months.',
    'The stage was then set for the election of the Illinois legislature which would, in turn, select Lincoln or Douglas.',
    'Goodwin described the group in her biography as a Team of Rivals.',
    'As a riverboat man, Lincoln initially favored those interests, but ultimately represented whoever hired him.',
    '1860 presidential election On May 9–10, 1860, the Illinois Republican State Convention was held in Decatur.',
    'Lincoln claimed Indians were antagonistic toward his father, Thomas Lincoln, and his young family.',
    'Internationally, Lincoln wanted to forestall foreign military aid to the Confederacy.',
    'Lincoln has often been portrayed by Hollywood, almost always in a flattering light.',
    'He was viewed by abolitionists as a champion of human liberty.',
    'The Confederacy selected Jefferson Davis as its provisional president on February 9, 1861.',
    'In 1863, Lincoln declared the final Thursday in November of that year to be a day of Thanksgiving.',
    'The Revenue Act of 1862 adopted rates that increased with income.',
    'This call forced states to choose sides.',
    'Lincoln believed the federal government had limited responsibility to the millions of freedmen.',
    'He also hired John George Nicolay as his personal secretary, who would remain in that role during the presidency.',
    'Taylor won and Lincoln hoped in vain to be appointed Commissioner of the General Land Office.',
    'States admitted to the Union West Virginia was admitted to the Union on June 20, 1863.',
    'Lincoln became a favorite exemplar for liberal intellectuals across the world.',
    'Lincoln denounced it as the product of a conspiracy of Democrats to support the Slave Power.',
    "Abraham then became increasingly distant from Thomas, in part due to his father's lack of education.",
    'On March 4, 1865, Lincoln delivered his second inaugural address.',
    'At the last minute, Grant decided to go to New Jersey to visit his children instead of attending the play.',
    'Lincoln ended the crisis by releasing the two diplomats.',
    "General Grant Grant's victories at the Battle of Shiloh and in the Vicksburg campaign impressed Lincoln.",
    'I had looked the party over and concluded that these were the very strongest men.',
    'He was deeply familiar with the Bible, quoting and praising it.',
    'The Radical Republicans criticized him for moving too slowly in abolishing slavery.',
    'He championed construction of the Illinois and Michigan Canal, and later was a Canal Commissioner.',
    'Lincoln at this time reviewed a draft of the Emancipation Proclamation with his cabinet.',
    'He felt such action could be taken only within the war powers of the commander-in-chief, which he planned to exercise.',
    'Lincoln was tall, strong, and athletic, and became adept at using an ax.',
    'That doomed amendment would have protected slavery in states where it already existed.',
    'The US issued paper currency for the first time, known as greenbacks—printed in green on the reverse side.',
    'Copperheads criticized Lincoln for refusing to compromise on slavery.',
    'Lincoln was born into poverty in a log cabin in Kentucky and was raised on the frontier primarily in Indiana.',
    "Lincoln's articulation of the issues gave him a national political presence.",
    'In Tennessee and Arkansas, Lincoln respectively appointed Johnson and Frederick Steele as military governors.',
    'He noted that Lincoln used ethnic slurs and told jokes that ridiculed blacks.',
    'People of the Northern states knew the Southern states would vote against Lincoln and rallied supporters for Lincoln.',
    'He supported the Wilmot Proviso, a failed proposal to ban slavery in any U.S. territory won from Mexico.',
    'But he also vowed not to surrender the forts.',
    'With the death of his son Edward in 1850 he more frequently expressed a dependence on God.',
    'The 1862 Morrill Land-Grant Colleges Act provided government grants for agricultural colleges in each state.',
    'Health Lincoln is believed to have had depression, smallpox, and malaria.',
    'The president ended his address with an appeal to the people of the South: "We are not enemies, but friends.',
    'After leading in the first six rounds of voting, he was unable to obtain a majority.',
    "Finally, Lincoln's Treasury Secretary, Salmon P. Chase, became Chief Justice.",
    'Historians have said he was "a classical liberal" in the 19th-century sense.',
    'On November 8, Lincoln carried all but three states, including 78 percent of Union soldiers.',
    "After Willie's death, he questioned the divine necessity of the war's severity.",
    'In a larger sense, the reaction was in response to the deaths of so many men in the war.',
    'Lincoln commented on his thought process, "We need the strongest men of the party in the Cabinet.',
    'In the early 1830s, he met Mary Owens from Kentucky.',
    'The president-elect evaded suspected assassins in Baltimore.',
    'Lincoln responded, "I could not afford to hang men for votes."',
    'He was assigned to the Committee on Post Office and Post Roads and the Committee on Expenditures in the War Department.',
    'Lincoln vetoed only four bills, including the Wade-Davis Bill with its harsh Reconstruction program.',
    'Mary kept house with the help of a hired servant and a relative.',
    "Their father, it seemed, was often too absorbed in his work to notice his children's behavior.",
    'The death of son Willie in February 1862 may have caused him to look toward religion for solace.',
    'He defined the war as dedicated to the principles of liberty and equality for all.',
    'Lincoln "was remarkably fond of children" and the Lincolns were not considered to be strict with their own.',
    'His petition was denied in Dred Scott v. Sandford (1857).',
    'He became county wrestling champion at the age of 21.',
    'By 1835, they were in a relationship but not formally engaged.',
    'She died on August 25, 1835, most likely of typhoid fever.',
    'Lincoln accepted the nomination with great enthusiasm and zeal.',
    'In 1849, he received a patent for a flotation device for the movement of boats in shallow water.',
    'After remaining in a coma for eight hours, Lincoln died at 7:22 in the morning on April 15.',
    'But Lincoln demonstrated intellectual leadership that brought him into contention.',
    'He never made a clear profession of Christian beliefs.',
    'Occasionally Mary prevailed on him to take a carriage ride, concerned that he was working too hard.',
    'I believe this government cannot endure permanently half slave and half free.',
    "Lincoln's assassination left him a national martyr.",
    'Union military strategy Lincoln took executive control of the war and shaped the Union military strategy.',
    'Lincoln suffered from "melancholy", a condition now thought to be clinical depression.',
    'When the Confederates protested forcing Confederate prisoners to fight Indians, Lincoln revoked the policy.',
    'While he is usually portrayed bearded, he did not grow a beard until 1860 at the suggestion of 11-year-old Grace Bedell.',
    'Stanton saluted and said, "Now he belongs to the ages."',
    "As Grant continued to weaken Lee's forces, efforts to discuss peace began.",
    '"Stanton and Lincoln virtually conducted the war together", say Thomas and Hyman.',
    'In 1839, Lincoln met Mary Todd in Springfield, Illinois, and the following year they became engaged.',
    'The National Banking Act created the system of national banks.',
    "During his presidency, Lincoln's policy toward Indians was driven by politics.",
    'Edward Baker Lincoln (Eddie), born in 1846, died February 1, 1850, probably of tuberculosis.',
    'Americans asked, "What would Lincoln do?"',
    'In 1861, Lincoln signed the second and third Morrill Tariffs, following the first enacted by Buchanan.',
    "Grant's bloody stalemates damaged Lincoln's re-election prospects, and many Republicans feared defeat.",
    'This first attempt fell short of the required two-thirds majority in the House of Representatives.',
    'His formal schooling was from itinerant teachers.',
    'Lincoln emerged as a formidable trial combatant during cross-examinations and closing arguments.',
    'At its convention, the Republicans selected Johnson as his running mate.',
    'McClellan then took months to plan his Virginia Peninsula Campaign.',
    'He never joined a church, although he frequently attended First Presbyterian Church with his wife beginning in 1852.',
    "The prior proclamation had been during James Madison's presidency 50 years earlier.",
    'Lincoln was concerned that Grant might be considering a presidential candidacy in 1864.',
    'Late in 1836, Lincoln agreed to a match with Owens if she returned to New Salem.',
    "Sherman's capture of Atlanta in September and David Farragut's capture of Mobile ended defeatism.",
    'Samuel Freeman Miller supported Lincoln in the 1860 election and was an avowed abolitionist.',
    'He emphasized defeat of the Confederate armies over destruction (which was considerable) for its own sake.',
    'He was the first Republican president and his victory was entirely due to his support in the North and West.',
    'She was the daughter of Robert Smith Todd, a wealthy lawyer and businessman in Lexington, Kentucky.',
    'State Republican parties stressed the perfidy of the Copperheads.',
    "Lincoln explains therein that the cause, purpose, and result of the war was God's will.",
    'He denounced secession as anarchy, and explained that majority rule had to be balanced by constitutional restraints.',
    'Many, though not all, in the South considered Lincoln as a man of outstanding ability.',
    'Some believed it was a conspiracy by the Confederacy to launch a war on the Northwestern front.',
    'The captain was killed in an Indian raid in 1786.',
    'Lincoln reacted to Union losses by mobilizing support throughout the North.',
    'Lincoln did not comment on the act until months later in his "Peoria Speech" in October 1854.',
    'Lincoln not only pulled off his strategy of gaining the nomination in 1846 but also won the election.',
    'Education and move to Illinois Lincoln was largely self-educated.',
    'Thomas and Nancy were members of a Separate Baptists church, which forbade alcohol, dancing, and slavery.',
    'He was self-educated and became a lawyer, Whig Party leader, Illinois state legislator, and U.S.',
    'Historians emphasized the widespread shock and sorrow, but noted that some Lincoln haters celebrated his death.',
    "McClellan, in turn, blamed the failure of the campaign on Lincoln's reservation of troops for the capitol.",
    'The family then migrated west, passing through New Jersey, Pennsylvania, and Virginia.',
    'Lincoln managed his own successful re-election campaign.',
    'In 1854, Lincoln was elected to the Illinois legislature but declined to take his seat.',
    'On April 1, 1865, Grant nearly encircled Petersburg in a siege.',
    'His legal reputation gave rise to the nickname "Honest Abe".',
    "Republicans linked Lincoln's name to their party.",
    'A former Democrat, Hannibal Hamlin of Maine, was nominated for vice president to balance the ticket.',
    'Lincoln disliked the hard labor associated with farm life.',
    'The Democratic Party was deeply split, with some leaders and most soldiers openly for Lincoln.',
    'Democrat Stephen Johnson Field, a previous California Supreme Court justice, provided geographic and political balance.',
    'In the runup to the election, he took an office in the Illinois state capitol to deal with the influx of attention.',
    'Lincoln argued that the testimony involved a dying declaration and was not subject to the hearsay rule.',
    'Furthermore, it was a national duty to ensure the republic stands in every state.',
    'I hate it because of the monstrous injustice of slavery itself.',
    'In Kentucky and Indiana, Thomas worked as a farmer, cabinetmaker, and carpenter.',
    'Through his entire public career, Lincoln had a proneness for quoting Scripture.',
    'Lincoln then declared his opposition to slavery which he repeated en route to the presidency.',
    'Lincoln is largely responsible for the Thanksgiving holiday.',
    "The appointments were both politically neutral and adroit on Lincoln's part.",
    'Since a person cannot sense during sleep they cannot have desire, which is the result of sensation.',
    'To a modern biologist, the explanation, not available to Aristotle, is convergent evolution.',
    "A contribution to our understanding of how to read Aristotle's scientific works.",
    'Influence More than 2300 years after his death, Aristotle remains one of the most influential people who ever lived.'
]
